version: '3.8'

services:
  # Open WebUI - Using official image
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: bookai-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      # Connect to our Vertex AI adapter instead of OpenAI
      - OPENAI_API_BASE_URL=http://vertex-adapter:8000/v1
      - OPENAI_API_KEY=dummy-key-for-vertex
      
      # Open WebUI configuration
      - WEBUI_NAME=BookAI
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-your-secret-key-here}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-true}
      
      # Database (Open WebUI manages its own SQLite by default)
      # For production, you can configure PostgreSQL here
      
      # Optional features
      - ENABLE_RAG=${ENABLE_RAG:-true}
      - ENABLE_WEB_SEARCH=${ENABLE_WEB_SEARCH:-false}
    depends_on:
      - vertex-adapter
    restart: unless-stopped
    networks:
      - bookai-network

  # ADK Orchestrator - Intelligent request routing
  adk-orchestrator:
    build: ./adk-orchestrator
    container_name: bookai-adk-orchestrator
    ports:
      - "8001:8000"  # Expose for debugging
    volumes:
      - ./config:/app/config:ro
    env_file:
      - .env
    environment:
      # Google Cloud Configuration (reuse existing)
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/${GOOGLE_APPLICATION_CREDENTIALS}
      # ADK-specific environment variables
      - GOOGLE_GENAI_USE_VERTEXAI=TRUE
    restart: unless-stopped
    networks:
      - bookai-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Vertex AI Adapter - Our custom service
  vertex-adapter:
    build: ./vertex-adapter
    container_name: bookai-vertex-adapter
    ports:
      - "8000:8000"  # Expose for debugging, not needed in production
    volumes:
      - ./config:/app/config:ro
    env_file:
      - .env
    environment:
      # Google Cloud Configuration
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/${GOOGLE_APPLICATION_CREDENTIALS}
      
      # Model Configuration
      - AI_MODEL=${AI_MODEL:-gemini-2.0-flash-exp}
      
      # Adapter Configuration
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # Knowledge Base Configuration
      - OPENWEBUI_API_BASE=http://open-webui:8080
      - OPENWEBUI_API_KEY=sk-18b7a0c99fba4fb4b42309d89cedc864
      
      # Orchestration Configuration
      - ADK_ORCHESTRATOR_URL=http://adk-orchestrator:8000
      - ENABLE_ORCHESTRATION=${ENABLE_ORCHESTRATION:-true}
    depends_on:
      - adk-orchestrator
    restart: unless-stopped
    networks:
      - bookai-network

  # Optional: PostgreSQL for Open WebUI (instead of SQLite)
  # Uncomment if you want to use PostgreSQL
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: bookai-postgres
  #   environment:
  #     - POSTGRES_DB=openwebui
  #     - POSTGRES_USER=openwebui
  #     - POSTGRES_PASSWORD=${DB_PASSWORD:-openwebui}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - bookai-network

volumes:
  open-webui-data:
  # postgres-data:  # Uncomment if using PostgreSQL

networks:
  bookai-network:
    driver: bridge